name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [20.x, 22.x, 24.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm run test --coverage

      - name: Build example Storybook
        run: pnpm run example:vite:build

      - name: Publish and test example Storybook
        if: matrix.node == '20.x' && matrix.os == 'ubuntu-latest'
        uses: chromaui/action@2a0b63f30233c48591844a46d451b9cf68128186 # v18.7.2
        with:
          projectToken: '574df7cc3736'
          # Don't wait until Chroma verified the build (for this we have the Github check)
          exitOnceUploaded: true
          storybookBuildDir: examples/vite/storybook-static/
          debug: true

      - name: Upload coverage
        if: matrix.node == '20.x' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
