on:
  push:
    branches:
      - main
name: Release
permissions:
  contents: write
  pull-requests: write
jobs:
  release-pr:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ secrets.RELEASE_PR_TOKEN }}

      # Format changelog, workaround for https://github.com/google-github-actions/release-please-action/issues/542
      # Taken from https://github.com/remarkablemark/release-please-extra-files-demo/blob/master/.github/workflows/release-please.yml
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ steps.release.outputs.pr }}
        with:
          token: ${{ secrets.RELEASE_PR_TOKEN }}
          fetch-depth: 0
          ref: ${{ fromJson(steps.release.outputs.pr).headBranchName }}

      - name: Configure Git user
        if: ${{ steps.release.outputs.pr }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git --no-pager show --name-only

      - name: Format CHANGELOG.md
        if: ${{ steps.release.outputs.pr }}
        run: npx oxfmt --write CHANGELOG.md .release-please-manifest.json

      - name: Commit
        if: ${{ steps.release.outputs.pr }}
        run: |
          git add CHANGELOG.md .release-please-manifest.json
          git commit -m 'chore: Format CHANGELOG.md' --no-verify

      - name: Push changes
        if: ${{ steps.release.outputs.pr }}
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # master
        with:
          github_token: ${{ secrets.RELEASE_PR_TOKEN }}
          branch: ${{ fromJson(steps.release.outputs.pr).headBranchName }}

  publish_npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    needs: [release-pr]
    if: needs.release-pr.outputs.release_created
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: corepack enable
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          ## we need at least npm 24 to use OIDC publishing
          ## at the same time we don't want to bump the node
          ## version in `package.json` as that would introduce
          ## a change to the package itself
          # node-version-file: package.json
          node-version: 24.16.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
